run:
  concurrency: 4
  timeout: 5m
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: true

severity:
  default-severity: error
  case-sensitive: true

linters-settings:
  errcheck:
    check-type-assertions: true

  exhaustive:
    check:
      - switch
      - map

  exhaustruct:
    exclude:
      - "^net/http.Client$"
      - "^net/http.Cookie$"
      - "^net/http.Request$"
      - "^net/http.Response$"
      - "^net/http.Server$"
      - "^net/http.Transport$"
      - "^net/url.URL$"
      - "^os/exec.Cmd$"
      - "^reflect.StructField$"

  revive:
    rules:
      - name: var-naming
        disabled: true

  stylecheck:
    checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]

  gocritic:
    settings:
      captLocal:
        paramsOnly: false
      underef:
        skipRecvDeref: false

  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      shadow:
        strict: true

  nolintlint:
    allow-no-explanation: [ funlen, lll ]
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dupl
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosec
    - lll
    - loggercheck
    - makezero
    - musttag
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - predeclared
    - promlinter
    - reassign
    - revive
    - sqlclosecheck
    - stylecheck
    - tenv
    - testableexamples
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
    - exhaustruct
    - gci