// Code generated by mockery v2.20.0. DO NOT EDIT.

package credentials

import mock "github.com/stretchr/testify/mock"

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields:
func (_m *MockProvider) Get() *Credentials {
	ret := _m.Called()

	var r0 *Credentials
	if rf, ok := ret.Get(0).(func() *Credentials); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Credentials)
		}
	}

	return r0
}

// MockProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Get() *MockProvider_Get_Call {
	return &MockProvider_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockProvider_Get_Call) Run(run func()) *MockProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Get_Call) Return(_a0 *Credentials) *MockProvider_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_Get_Call) RunAndReturn(run func() *Credentials) *MockProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockProvider(t mockConstructorTestingTNewMockProvider) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
