// Code generated by mockery v2.20.0. DO NOT EDIT.

package colorize

import mock "github.com/stretchr/testify/mock"

// MockConsole is an autogenerated mock type for the Console type
type MockConsole struct {
	mock.Mock
}

type MockConsole_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsole) EXPECT() *MockConsole_Expecter {
	return &MockConsole_Expecter{mock: &_m.Mock}
}

// IsColored provides a mock function with given fields:
func (_m *MockConsole) IsColored() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockConsole_IsColored_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsColored'
type MockConsole_IsColored_Call struct {
	*mock.Call
}

// IsColored is a helper method to define mock.On call
func (_e *MockConsole_Expecter) IsColored() *MockConsole_IsColored_Call {
	return &MockConsole_IsColored_Call{Call: _e.mock.On("IsColored")}
}

func (_c *MockConsole_IsColored_Call) Run(run func()) *MockConsole_IsColored_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsole_IsColored_Call) Return(_a0 bool) *MockConsole_IsColored_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsole_IsColored_Call) RunAndReturn(run func() bool) *MockConsole_IsColored_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockConsole interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockConsole creates a new instance of MockConsole. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockConsole(t mockConstructorTestingTNewMockConsole) *MockConsole {
	mock := &MockConsole{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
