name: CI / Automated testing

on:
  workflow_dispatch:

  pull_request:
    branches:
      - '**'

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Run "go mod download"
        run: make deps

  build-and-test:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Run "go mod download"
        run: make deps

      - name: Run "go build"
        run: make build

      - name: Run "go fmt"
        run: make format

      - name: Run "golangci-lint"
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2

      - name: Run "go test"
        run: make test

