name: CI / Coverage

on:
  workflow_dispatch:

  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Run "go mod download"
        run: make deps

      - name: Run "go test"
        run: make coverage

      - name: Send reports to Codeclimate
        uses: paambaati/codeclimate-action@v3.2.0
        if: ${{ hashFiles('**/coverage.out') }}
        env:
          CC_TEST_REPORTER_ID: 769f4877f65d09b04051904aa3f6cc8e2da60d0604f49571f925c41e0fd14847
        with:
          coverageLocations: '**/coverage.out:gocov'
